---@class HighlightOpt
---@field style string
---@field link? string if defined, everything else is ignored
---@field guifg string
---@field guibg string
---@field guisp string
---@field ctermfg string
---@field ctermbg string

---@class Quick
---@field command fun(name: string, command: string|function, opts?: table) Creates a command from provided specifics.
---@field normal fun(mode: string, motion: string, special: boolean?) Executes a command in normal mode.
---@field selection_contents fun(): string Returns the contents of the visually selected region.
---@field buffer_command fun(name: string, command: string|function, opts?: table) Creates a command from provided specifics on current buffer.
---@field call_and_centre fun(fn: fun()) Pushes the current location to the jumplist and calls the fn callback, then centres the cursor.
---@field cmd_and_centre fun(cmd: string) Pushes the current location to the jumplist and calls the cmd, then centres the cursor.
---@field highlight fun(group: string, opt: HighlightOpt) --Create a highlight group.

---@class ListItem
---@field bufnr number
---@field lnum number
---@field col number
---@field text string
---@field type string the type of the item. We assign `Z`.

---@class Extmarks
---@field unique_id string
---@field group number
---@field ns number
---@field listener_name string
---@field sign_group string
---@field qf_sign_hl HighlightOpt
---@field qf_ext_hl HighlightOpt
---@field local_sign_hl HighlightOpt
---@field local_ext_hl HighlightOpt
---@field set_signs boolean
---@field qf_sigil string
---@field qf_sign_hl_group string
---@field local_sign_hl_group string
---@field local_sigil string
---@field priority number
---@field set_extmarks boolean
---@field qf_badge string
---@field qf_ext_hl_group string
---@field loc_badge string
---@field loc_ext_hl_group string
